[theme]
base="dark"  # Usar o tema base escuro
primaryColor="#1565C0"
backgroundColor="#0A0F14"  # Fundo bem escuro, quase preto, semelhante ao da imagem
secondaryBackgroundColor="#161D24"  # Cinza escuro para contrastar com o fundo principal
textColor="#BFBFBF"  # Cinza claro, para garantir boa legibilidade
font="sans serif"  # Manter uma fonte moderna e limpa
