[theme]
# Base escura para harmonizar com o exemplo fornecido.
base = "dark"
primaryColor = "#506874"  # Amarelo vibrante para destacar elementos principais.
backgroundColor = "#223843"  # Azul escuro para o fundo principal.
secondaryBackgroundColor = "#18262D"  # Azul médio para separar seções.
textColor = "#F8F9FA"  # Branco claro para textos legíveis.
font = "sans serif"

[global]
disableWidgetStateDuplicationWarning = true
showWarningOnDirectExecution = false

[logger]
level = "error"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[runner]
fastReruns = true

[server]
runOnSave = true
headless = false
enableCORS = true
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
gatherUsageStats = true