[theme]
# Escolha uma base clara para um visual mais parecido com o exemplo.
base = "light"
primaryColor = "#FFC107"  # Amarelo vibrante para destacar elementos principais.
backgroundColor = "#F4F6F8"  # Cinza claro para o fundo principal.
secondaryBackgroundColor = "#FFFFFF"  # Branco para áreas de destaque.
textColor = "#343A40"  # Cinza escuro para um texto claro e legível.
font = "sans serif"

[global]
disableWidgetStateDuplicationWarning = true
showWarningOnDirectExecution = false

[logger]
level = "error"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[runner]
fastReruns = true

[server]
runOnSave = true
headless = false
enableCORS = true
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
gatherUsageStats = true
